# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71e5e69f40afad308b99b2d7dea1761786239f9ec515ccc993761cfce1c1b2d9f156cc3f2adf58c13a65c8ff4d05760c68157776d0fec6cf2af1d9443ea0097b

test:
  secret_key_base: e41a50dfbfbed6f1615fabf4ae19963d393251341794ec8f65b1d4de0f8699042e3add52f7be6810389c327f27456ddf4ece2d5002ac698de649a5e49173205f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
